### ISSUE TITLE
Ability to change line color, thickness, and type (dash, dot-dash, continuous etc.)

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#136]
Color should implement the Munsell-Color-Space

**Comment by Methusshan25** [comment]
After researching packages for drawing in javascript and vue, the package vue-drawing-canvas seems to be most suitable for our project. It offers a lot of options and can easily implemented into the project. 
Package: https://www.npmjs.com/package/vue-drawing-canvas

**Comment by Methusshan25** [comment]
This was tested in a small testpage, where a canvas was implemented with a button to change the color and switch between pen and eraser. 
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/56478334/4191d3f3-c17c-4b39-96ef-fb6040309f94)
