### ISSUE TITLE
Landing page instead of throwing users directly to activity overview

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#169]
We should design and create a dedicated landing page for the fieldbook. This should give a short description on what the 3d fieldbook is and maybe show a few preview screenshots of the system.

You also should be able to download our offline usable desktop apps from there and login to the system.

**Comment by Me0li** [comment]
I'll take care of it

**Comment by JuHardtung** [comment]
We should finalize the landing page before the evaluation.

Currently missing are:

- a short text introduction, what the fieldbook even is
- (maybe a short introduction into the Stellenkartensystem with a few pictures)
- mentioning that you can create an account, or just use the system
- mentioning that you can download the whole thing for local, offline usage

**Comment by JuHardtung** [comment]
@Me0li I saw your update to the landing page. This looks quite good already and has the important information. Just two small things I noticed:

- when switching to English mode, the "Stellenkarten-image stays the same. I know this might be a bit cumbersome to change this dynamically to an English version, but I just wanted to note it down.
- also when switching to English mode, the table content stays German

**Comment by Me0li** [comment]
I will take the feedback into account and already have an idea for a solution

**Comment by Me0li** [comment]
The translations are now all inserted, unfortunately these are not updated immediately when you change the language. Only when you firstly switch to another page and then go back to the landing page they get updated

**Comment by Me0li** [comment]
That immediately seemed so familiar to me. I think we will have to live with that here too

**Comment by JuHardtung** [comment]
We could force a page reload when the user changes the language. But this might cause other side effects...

 I will look into that.

**Comment by JuHardtung** [comment]
Commit 089f87f39b324d9fbc28729e8e3bb911b2e64e73 fixes all issues with non-persistent language settings and the vuetify-tables that weren't properly translated
