### ISSUE TITLE
account pages should not be scrollable

### ISSUE THREAD

**Issue by Methusshan25** [TMink/Digitales-3D-Feldbuch-Projekt-3-#177]
The account pages are scrollable, which doesn't make sense, because there is no content on the bottom. 
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/56478334/c33ad8c4-e1f1-466e-9073-4fc1d41154c2)
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/56478334/31f195ff-751c-417e-89d8-b85dcb5f0920)

**Comment by JuHardtung** [comment]
These pages are so far just for functionality and not fully polished. Finalization of these things have to wait until Issue https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/issues/137 has been resolved. Though @Me0li is currently working on that
