### ISSUE TITLE
The first version of the styleguide needs to be reviewd and expanded

### ISSUE THREAD

**Issue by Me0li** [TMink/Digitales-3D-Feldbuch-Projekt-3-#178]
Our styleguide is ready in version 1.0 and now needs to be expanded and checked. Only then should we start checking our system to see whether the style guide is being followed everywhere

[Uploading Style guide - Digital 3D Fieldbook.pdf…]()

**Comment by JuHardtung** [comment]
The link doesn't work

**Comment by Me0li** [comment]
I'll try again
[Uploading Style guide - Digital 3D Fieldbook.pdf…]()

**Comment by Me0li** [comment]
Github won't upload the file here, so instead you can find the pdf [here](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/blob/main/Dokumente/Style%20guide%20-%20Digital%203D%20Fieldbook.pdf)

**Comment by JuHardtung** [comment]
It would be nice to have the icon names directly within the document, so you don't have to search for them in the material icon library.

**Comment by JuHardtung** [comment]
The styleguide is missing our toast messages. They should give feedback to users if an action was successful or not and/or has finished.

![XBruJBWIfB](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/dce890e1-5749-49b7-b378-f8fb26845881)

![chrome_mAguJWIZoV](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/cb194485-c54f-49b9-9a92-35127159993c)
