### ISSUE TITLE
Weird artifacts/unsmooth lines in technical drawings

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#211]
As seen below, there are some weird artifacts when simply drawing with the pen tool. I don't know if this has something to do with pixel size of the canvas, or maybe screen size, or maybe even drawing speed.

Regardless, this will have to be investigated, this would otherwise destroy the usefulness of the whole technical drawing.

![chrome_B0mNnwGw4o](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/f412ad1b-60fb-4274-9c8f-68f779542808)

**Comment by Methusshan25** [comment]
I pushed a commit, which should fix this problem. I have not set all settings in the canvas yet and this resulted probably in those unsmooth lines. How i set all settings for the style of the lines. 
Now it should look like this:

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/56478334/d4763f1f-f58f-4e1e-85f2-2623a56fe652)
