### ISSUE TITLE
Better design for activities, that are synchronized with backend

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#216]
Currently, we simply show a small, gray text that shows when this activity was last synchronized with the backend. The design for this was just meant to be temporary, so we should find something better before the evaluation.

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/c78983d8-ad36-4bf0-ba5d-d0f6d6c2e6a0)

Another thing is the options button on the right. Orange is the normal color, when an activity is assigned to an editor (which is then able to be synchronized to the backend) and red is when the activity is just local and not assigned to an account. This color scheme is not really self-explanatory and should be changed somehow.

**Comment by Me0li** [comment]
I'll think of something
