### ISSUE TITLE
Better design for any objects that are synchronized with the backend

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#217]
As already solved in #216, we need to do the same treatment to all other objects (places, positions, images, models)

Example in PlacesOverview:

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/74ba7af1-0131-4ae5-afd6-eba30ca39ddb)

**Comment by Me0li** [comment]
Should the synchronization status really be displayed for each individual image or 3D model? These are always linked to a corresponding activity/position/place and are either completely local or completely synchronized.

**Comment by JuHardtung** [comment]
But what is with the edge case that you synchronized the whole activity with all places/positions etc.

Then you lose Internet connection or log out and then add new data. Then you would only have partially synchronized your data.

**Comment by Me0li** [comment]
In this case you would notice on one of the overview pages that not all of your positions/locations/activities are fully synchronized
