### ISSUE TITLE
Light Theme has wrong list hover color

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#220]
The hover color on any vuetify-table always shows the dark-mode color, even when using light-mode.

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/313f3816-5f1c-4a4c-8a1b-1bd5b6e62749)

Generally, some pages don't work optimally in light-mode.

**Comment by Me0li** [comment]
We had already noticed the problem in Xanten. I can't remember why exactly, but back then I had to set the color for both themes the same. I'll look into this once more
