### ISSUE TITLE
3d-part rotation doesn't rotate around center of mass

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#223]
As seen in the GIF below, the rotation doesn't rotate the model around its center of mass. I don't know if this is an issue of the model itself, but we used this exact model for testing purposes before without any issues.

![rotationFail](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/86fdc497-21c9-4411-a5b8-2e14a28b1de8)

**Comment by TMink** [comment]
With the new barycenter calculation, this problem no longer exists. With each new call of the 3D-Part, the center of mass is recalculated depending on the existing models.
